<ManufacturerList>:
    FloatLayout:
        size:root.width, root.height
        MDBoxLayout:
            id:manufacturer_list
            orientation: "vertical"
            size:root.width*0.9, root.height*0.9
            size_hint: None, None
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            MDBoxLayout:
                orientation: "horizontal"

                id:product_form
                size_hint: 1, 0.1

